In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,4,7])

In [3]:
arr

array([2, 3, 4, 7])

In [4]:
type(arr)

numpy.ndarray

In [5]:
a1=np.array([[2,5],[7,5],[9,7]])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a1

array([[2, 5],
       [7, 5],
       [9, 7]])

In [9]:
type(a1[0][0])

numpy.int32

In [12]:
l = np.array(0,10, 1,dtype=int)

ValueError: only 2 non-keyword arguments accepted

In [13]:
l = np.arrange(1,10)

AttributeError: 'module' object has no attribute 'arrange'

In [16]:
l=np.arange(1,10,1.3)

In [17]:
l

array([ 1. ,  2.3,  3.6,  4.9,  6.2,  7.5,  8.8])

In [20]:
l = np.arange(0,100,12.5, dtype=np.float64)

In [21]:
l

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5])

In [22]:
l1 = np.linspace(0,100,5, dtype=np.float64)

In [23]:
l1

array([   0.,   25.,   50.,   75.,  100.])

In [27]:
print(np.array([10,20,30,40,50,60]).reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [28]:
print(np.matrix([[0,5],[4,6],[10,100]]))

[[  0   5]
 [  4   6]
 [ 10 100]]


In [29]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
print(np.zeros((3,5))

SyntaxError: unexpected EOF while parsing (<ipython-input-32-14f73c5552bd>, line 1)

In [37]:
print( np.ones( (4,3) ,dtype=np.float64) )

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [38]:
arr1 =np.array([25, 56, 12, 85, 34, 75])

In [39]:
arr2 = np.array([42, 3, 86, 32, 856, 46])

In [40]:
arr1.shape

(6L,)

In [42]:
np.random.rand(3)

array([ 0.73468422,  0.85988885,  0.53505801])

In [53]:
Narr = np.array(arr1.shape)

In [49]:
Narr

array([6], dtype=int64)

In [50]:
Narr = np.random.rand()

In [51]:
Narr

0.9953286803511256

In [54]:
Narr.shape

(1L,)

In [55]:
Narr

array([6], dtype=int64)

In [57]:
Narr = np.random.rand(len(arr1))

In [58]:
Narr

array([ 0.51680008,  0.93897525,  0.32064925,  0.47844969,  0.21738291,
        0.75999445])

In [59]:
arr1

array([25, 56, 12, 85, 34, 75])

In [62]:
arr1.astype(complex)

array([ 25.+0.j,  56.+0.j,  12.+0.j,  85.+0.j,  34.+0.j,  75.+0.j])

In [64]:
arr1 = arr1.astype(complex)

In [65]:
arr1

array([ 25.+0.j,  56.+0.j,  12.+0.j,  85.+0.j,  34.+0.j,  75.+0.j])

In [67]:
type(arr1[0])

numpy.complex128

In [68]:
arr1_mat = arr1.reshape(2,3)

In [69]:
arr1_mat

array([[ 25.+0.j,  56.+0.j,  12.+0.j],
       [ 85.+0.j,  34.+0.j,  75.+0.j]])

In [70]:
arr2_mat = arr2.reshape(2,3)

In [71]:
arr2_mat

array([[ 42,   3,  86],
       [ 32, 856,  46]])

In [61]:
arr1

array([25, 56, 12, 85, 34, 75])

In [73]:
arr1_mat+arr2_mat

array([[  67.+0.j,   59.+0.j,   98.+0.j],
       [ 117.+0.j,  890.+0.j,  121.+0.j]])

In [74]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [75]:
np.arange(4)

array([0, 1, 2, 3])

In [76]:
b=np.arange(4)

In [77]:
b.shape

(4L,)

In [78]:
b.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [79]:
b

array([0, 1, 2, 3])

In [80]:
b.shape

(4L,)

In [81]:
S_X = np.matrix([[2,5,6,5],[4,8,6,5]])

In [82]:
S_X

matrix([[2, 5, 6, 5],
        [4, 8, 6, 5]])

In [84]:
S_Y = np.array([[6,7,5,9], [7,5,6,4]])

In [85]:
S_Y

array([[6, 7, 5, 9],
       [7, 5, 6, 4]])

In [86]:
S_X - S_Y

matrix([[-4, -2,  1, -4],
        [-3,  3,  0,  1]])

In [88]:
S_X[S_X<2]

matrix([], shape=(1L, 0L), dtype=int32)

In [91]:
S_X[0].mean()

4.5

In [92]:
S_X.cumsum()

matrix([[ 2,  7, 13, 18, 22, 30, 36, 41]])

In [94]:
S_Y[0].cumsum()

array([ 6, 13, 18, 27])

In [100]:
m = np.zeros((4,4), dtype=np.int32)

In [101]:
m

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [107]:
np.diagonal([3,4],[5,6])

TypeError: an integer is required

In [109]:
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [116]:
np.diag([4,5,6],1)

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

In [119]:
np.diag([2,3],-1)

array([[0, 0, 0],
       [2, 0, 0],
       [0, 3, 0]])

In [121]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])

In [127]:
mat

array([['abc', 'A'],
       ['def', 'B'],
       ['ghi', 'C'],
       ['jkl', 'D']],
      dtype='|S3')

In [128]:
arr = np.array(['abc','dfe','ghi','kjl'])

In [129]:
arr

array(['abc', 'dfe', 'ghi', 'kjl'],
      dtype='|S3')

In [130]:
mat == arr

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [136]:
mat[mat[:,0] == arr]

array([['abc', 'A'],
       ['ghi', 'C']],
      dtype='|S3')

In [139]:
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])

In [140]:
mat

array([[ 1, 21,  3],
       [ 5,  4,  2],
       [56, 12,  4]])

In [144]:
np.sort(mat, axis=0, 1)

SyntaxError: non-keyword arg after keyword arg (<ipython-input-144-7b42469746aa>, line 1)

In [146]:
mat

array([[ 1, 21,  3],
       [ 5,  4,  2],
       [56, 12,  4]])

In [147]:
mat[mat[:,1].argsort()]

array([[ 5,  4,  2],
       [56, 12,  4],
       [ 1, 21,  3]])

In [148]:
mat[:,1].argsort()

array([1, 2, 0], dtype=int64)

In [151]:
mat[[1,2,0]]

array([[ 5,  4,  2],
       [56, 12,  4],
       [ 1, 21,  3]])

In [152]:
mat[1]

array([5, 4, 2])

In [155]:
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])

In [156]:
arr

array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [157]:
np.argpartition(arr,3)

array([4, 6, 3, 1, 8, 2, 7, 9, 5, 0], dtype=int64)

In [158]:
arr

array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [159]:
np.argpartition(arr, 3)

array([4, 6, 3, 1, 8, 2, 7, 9, 5, 0], dtype=int64)

In [160]:
arr.argpartition(3)

array([4, 6, 3, 1, 8, 2, 7, 9, 5, 0], dtype=int64)

In [161]:
arr

array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [162]:
arr = np.argpartition(arr, 3)

In [163]:
arr

array([4, 6, 3, 1, 8, 2, 7, 9, 5, 0], dtype=int64)

In [164]:
arr

array([4, 6, 3, 1, 8, 2, 7, 9, 5, 0], dtype=int64)

In [165]:
arr = np.array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [170]:
arr[np.argpartition(arr,6)][-4:]

array([ 45,  50, 590,  90])

In [172]:
np.tril_indices?

In [175]:
np.diag_indices(4,2)

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [99]:
m

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [96]:
m

array([ 0.,  0.,  0.,  0.])

In [19]:
l

array([  1. ,  13.5,  26. ,  38.5,  51. ,  63.5,  76. ,  88.5])